fix python3 link

diff --git a/common.yml b/common.yml
--- a/common.yml
+++ b/common.yml
@@ -677,6 +677,18 @@ functions:
           venv='venv'
           venvNonWindows () { . "$venv"/bin/activate; python3 -m pip install boto3; }
           venvWindows () { . "$venv"/Scripts/activate; pip install boto3; }
+
+          if command -v python3; then
+              echo 'python3 exits'
+          elif command -v /opt/mongodbtoolchain/v3/bin/python3; then
+              # system python3 doesn't exist
+              echo 'create link to mongodbtoolchain python3'
+              ln -s /opt/mongodbtoolchain/v2/bin/python3 /usr/local/bin/python3
+          else
+              echo "python3 cannot be found!"
+              exit 1
+          fi
+
           if [ -f "$venv"/bin/activate ]; then
             echo 'activating existing virtualenv'
             venvNonWindows
